name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    # Your existing 'tests' job, exactly as defined earlier.
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Force Failure
        run: go test -cover ./...

  style:
    # The new 'style' job
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Check Formatting
        run: test -z $(go fmt ./...)
